### ISSUE TITLE
Regarding Google Policies

### ISSUE THREAD

**Issue by jonathansampson** [Kippykip/gab-dissenter-extension#1]
The extension states in the Chrome Web Store that it "…is modified to comply with the Google Web Store policies." Is there any more information regarding this? I don't see any significant changes because finer controls for Facebook, and aesthetic modifications. Thank you in advance for your input!

**Comment by Kippykip** [comment]
Google never actually stated a reason for the removal afaik, they just removed it due to media articles against it since it was made by Gab.
So I guess you could say dissenter technically followed the guidelines since the beginning lmao, but the aesthetic changes made here were actually just to remove the G/Gab logos hoping that it makes it now comply with their vague policies.

**Comment by jonathansampson** [comment]
Thank you for the clarification!
